package level1;

public class MySQL {

	//이름이 없는 동물의 아이디
// SELECT animal_id FROM animal_ins WHERE name IS NULL;
	
	
	
	//모든 레코드 조회하기
//	SELECT ANIMAL_ID, ANIMAL_TYPE, DATETIME, INTAKE_CONDITION, NAME, SEX_UPON_INTAKE
//	FROM ANIMAL_INS 
//	ORDER BY  ANIMAL_ID ASC;
	
	
	
	//이름이 있는 동물의 아이디
//	SELECT ANIMAL_ID 
//	FROM ANIMAL_INS
//	WHERE NAME IS NOT NULL
//	ORDER BY ANIMAL_ID ASC;
	
	
	
	//역순 정렬하기
//	SELECT NAME, DATETIME
//	FROM ANIMAL_INS
//	ORDER BY ANIMAL_ID DESC;
	
	
	
	
	//어린 동물 찾기
//	SELECT ANIMAL_ID, NAME
//	FROM ANIMAL_INS 
//	WHERE INTAKE_CONDITION NOT IN('Aged')
//	ORDER BY ANIMAL_ID ASC;
//  SELECT ANIMAL_ID , NAME FROM ANIMAL_INS WHERE INTAKE_CONDITION != "Aged"
	
	
	
	//최댓값 구하기
//	SELECT MAX(DATETIME) AS "시간"
//	FROM ANIMAL_INS;

	
	//아픈 동물 찾기
//	SELECT ANIMAL_ID, NAME
//	FROM ANIMAL_INS
//	WHERE INTAKE_CONDITION = 'Sick'
//	ORDER BY ANIMAL_ID ASC;
	
	
	//동물의 아이디와 이름
//	SELECT ANIMAL_ID,NAME
//	FROM ANIMAL_INS
//	ORDER BY ANIMAL_ID ASC;
	
	
	
	//여러 기준으로 정렬하기
//	SELECT ANIMAL_ID,NAME,DATETIME
//	FROM ANIMAL_INS
//	ORDER BY NAME ASC, DATETIME DESC;
	
	
	//상위 n개 레코드
//	SELECT NAME
//	FROM ANIMAL_INS
//	ORDER BY DATETIME ASC LIMIT 1;
//LIMIT 를 이용해 상위 N개 행만 조회
//limit 0, 1 : 위에서 0부터 1까지의 정보 추출
//limit 1 : 위에서 1개의 정보 추출
	
	
}


